# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AssistantClient.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowClient(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 327)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_Valider = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_Valider.setGeometry(QtCore.QRect(10, 30, 471, 271))
        self.tabWidget_Valider.setObjectName("tabWidget_Valider")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 421, 211))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_NewClient1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_NewClient1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_NewClient1.setObjectName("verticalLayout_NewClient1")
        self.horizontalLayout_NewClient2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_NewClient2.setObjectName("horizontalLayout_NewClient2")
        self.verticalLayout_NewClient4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_NewClient4.setObjectName("verticalLayout_NewClient4")
        self.label_Entreprise = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_Entreprise.setObjectName("label_Entreprise")
        self.verticalLayout_NewClient4.addWidget(self.label_Entreprise)
        self.label_Name = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_Name.setObjectName("label_Name")
        self.verticalLayout_NewClient4.addWidget(self.label_Name)
        self.label_Forename = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_Forename.setObjectName("label_Forename")
        self.verticalLayout_NewClient4.addWidget(self.label_Forename)
        self.label_Mail = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_Mail.setObjectName("label_Mail")
        self.verticalLayout_NewClient4.addWidget(self.label_Mail)
        self.horizontalLayout_NewClient2.addLayout(self.verticalLayout_NewClient4)
        self.verticalLayout_NewClient3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_NewClient3.setObjectName("verticalLayout_NewClient3")
        self.lineEdit_Entreprise = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_Entreprise.setObjectName("lineEdit_Entreprise")
        self.verticalLayout_NewClient3.addWidget(self.lineEdit_Entreprise)
        self.lineEdit_ContactName = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_ContactName.setObjectName("lineEdit_ContactName")
        self.verticalLayout_NewClient3.addWidget(self.lineEdit_ContactName)
        self.lineEdit_ContactForename = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_ContactForename.setObjectName("lineEdit_ContactForename")
        self.verticalLayout_NewClient3.addWidget(self.lineEdit_ContactForename)
        self.lineEdit_Mail = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_Mail.setObjectName("lineEdit_Mail")
        self.verticalLayout_NewClient3.addWidget(self.lineEdit_Mail)
        self.horizontalLayout_NewClient2.addLayout(self.verticalLayout_NewClient3)
        self.verticalLayout_NewClient1.addLayout(self.horizontalLayout_NewClient2)
        self.pushButton_Valider = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_Valider.setObjectName("pushButton_Valider")
        self.verticalLayout_NewClient1.addWidget(self.pushButton_Valider)
        self.tabWidget_Valider.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 20, 421, 211))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_ModClient1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_ModClient1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_ModClient1.setObjectName("verticalLayout_ModClient1")
        self.comboBox_modClient = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBox_modClient.setObjectName("comboBox_modClient")
        self.verticalLayout_ModClient1.addWidget(self.comboBox_modClient)
        self.horizontalLayout_ModClient2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ModClient2.setObjectName("horizontalLayout_ModClient2")
        self.verticalLayout_ModClient4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ModClient4.setObjectName("verticalLayout_ModClient4")
        self.labe_ModEntreprise = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.labe_ModEntreprise.setObjectName("labe_ModEntreprise")
        self.verticalLayout_ModClient4.addWidget(self.labe_ModEntreprise)
        self.label_ModContactName = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_ModContactName.setObjectName("label_ModContactName")
        self.verticalLayout_ModClient4.addWidget(self.label_ModContactName)
        self.label_ModContactForename = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_ModContactForename.setObjectName("label_ModContactForename")
        self.verticalLayout_ModClient4.addWidget(self.label_ModContactForename)
        self.label_ModMail = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_ModMail.setObjectName("label_ModMail")
        self.verticalLayout_ModClient4.addWidget(self.label_ModMail)
        self.horizontalLayout_ModClient2.addLayout(self.verticalLayout_ModClient4)
        self.verticalLayout_ModClient3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ModClient3.setObjectName("verticalLayout_ModClient3")
        self.lineEdit_ModEntreprise = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_ModEntreprise.setObjectName("lineEdit_ModEntreprise")
        self.verticalLayout_ModClient3.addWidget(self.lineEdit_ModEntreprise)
        self.lineEdit_ModContactName = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_ModContactName.setObjectName("lineEdit_ModContactName")
        self.verticalLayout_ModClient3.addWidget(self.lineEdit_ModContactName)
        self.lineEdit_ModContactForename = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_ModContactForename.setObjectName("lineEdit_ModContactForename")
        self.verticalLayout_ModClient3.addWidget(self.lineEdit_ModContactForename)
        self.lineEdit_ModMail = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_ModMail.setObjectName("lineEdit_ModMail")
        self.verticalLayout_ModClient3.addWidget(self.lineEdit_ModMail)
        self.horizontalLayout_ModClient2.addLayout(self.verticalLayout_ModClient3)
        self.verticalLayout_ModClient1.addLayout(self.horizontalLayout_ModClient2)
        self.pushButton_ModValider = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_ModValider.setObjectName("pushButton_ModValider")
        self.verticalLayout_ModClient1.addWidget(self.pushButton_ModValider)
        self.tabWidget_Valider.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(30, 20, 421, 211))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_SupprClient1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_SupprClient1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_SupprClient1.setObjectName("verticalLayout_SupprClient1")
        self.comboBox_supprClient = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        self.comboBox_supprClient.setObjectName("comboBox_supprClient")
        self.verticalLayout_SupprClient1.addWidget(self.comboBox_supprClient)
        self.pushButton_SupprValider = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.pushButton_SupprValider.setObjectName("pushButton_SupprValider")
        self.verticalLayout_SupprClient1.addWidget(self.pushButton_SupprValider)
        self.tabWidget_Valider.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_Valider.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Entreprise.setText(_translate("MainWindow", "Entreprise"))
        self.label_Name.setText(_translate("MainWindow", "Nom du contact"))
        self.label_Forename.setText(_translate("MainWindow", "Prénom du Contact"))
        self.label_Mail.setText(_translate("MainWindow", "Mail du Contact"))
        self.pushButton_Valider.setText(_translate("MainWindow", "Valider"))
        self.tabWidget_Valider.setTabText(self.tabWidget_Valider.indexOf(self.tab), _translate("MainWindow", "Client"))
        self.labe_ModEntreprise.setText(_translate("MainWindow", "Entreprise"))
        self.label_ModContactName.setText(_translate("MainWindow", "Nom du Contact"))
        self.label_ModContactForename.setText(_translate("MainWindow", "Prénom du Contact"))
        self.label_ModMail.setText(_translate("MainWindow", "E-Mail"))
        self.pushButton_ModValider.setText(_translate("MainWindow", "Valider"))
        self.tabWidget_Valider.setTabText(self.tabWidget_Valider.indexOf(self.tab_2), _translate("MainWindow", "Modifier un Client"))
        self.pushButton_SupprValider.setText(_translate("MainWindow", "Supprimer"))
        self.tabWidget_Valider.setTabText(self.tabWidget_Valider.indexOf(self.tab_3), _translate("MainWindow", "Supprimer un Client"))
