# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'portefeuille.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowPortefeuille(object):
    def setupUi(self, MainWindowPortefeuille):
        MainWindowPortefeuille.setObjectName("MainWindowPortefeuille")
        MainWindowPortefeuille.resize(1483, 803)
        self.centralwidget = QtWidgets.QWidget(MainWindowPortefeuille)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_unlockClient = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_unlockClient.sizePolicy().hasHeightForWidth())
        self.btn_unlockClient.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/unlock-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_unlockClient.setIcon(icon)
        self.btn_unlockClient.setObjectName("btn_unlockClient")
        self.gridLayout.addWidget(self.btn_unlockClient, 0, 3, 1, 1)
        self.comboBox_clients = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_clients.sizePolicy().hasHeightForWidth())
        self.comboBox_clients.setSizePolicy(sizePolicy)
        self.comboBox_clients.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox_clients.setObjectName("comboBox_clients")
        self.gridLayout.addWidget(self.comboBox_clients, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_portefeuilles = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_portefeuilles.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox_portefeuilles.setObjectName("comboBox_portefeuilles")
        self.gridLayout.addWidget(self.comboBox_portefeuilles, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.btn_unlockPortefeuille = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_unlockPortefeuille.sizePolicy().hasHeightForWidth())
        self.btn_unlockPortefeuille.setSizePolicy(sizePolicy)
        self.btn_unlockPortefeuille.setIcon(icon)
        self.btn_unlockPortefeuille.setObjectName("btn_unlockPortefeuille")
        self.gridLayout.addWidget(self.btn_unlockPortefeuille, 1, 3, 1, 1)
        self.btn_chooseClient = QtWidgets.QPushButton(self.groupBox)
        self.btn_chooseClient.setObjectName("btn_chooseClient")
        self.gridLayout.addWidget(self.btn_chooseClient, 0, 2, 1, 1)
        self.btn_choosePortefeuille = QtWidgets.QPushButton(self.groupBox)
        self.btn_choosePortefeuille.setObjectName("btn_choosePortefeuille")
        self.gridLayout.addWidget(self.btn_choosePortefeuille, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_newPortefeuille = QtWidgets.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/add-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_newPortefeuille.setIcon(icon1)
        self.btn_newPortefeuille.setObjectName("btn_newPortefeuille")
        self.horizontalLayout.addWidget(self.btn_newPortefeuille)
        self.label_portefeuilleChoisi = QtWidgets.QLabel(self.groupBox)
        self.label_portefeuilleChoisi.setObjectName("label_portefeuilleChoisi")
        self.horizontalLayout.addWidget(self.label_portefeuilleChoisi)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/checkmark-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_dateChoisie = QtWidgets.QLabel(self.groupBox)
        self.label_dateChoisie.setObjectName("label_dateChoisie")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_dateChoisie)
        self.lineEdit_dateChoisie = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dateChoisie.sizePolicy().hasHeightForWidth())
        self.lineEdit_dateChoisie.setSizePolicy(sizePolicy)
        self.lineEdit_dateChoisie.setReadOnly(True)
        self.lineEdit_dateChoisie.setObjectName("lineEdit_dateChoisie")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_dateChoisie)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox)
        self.calendarWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_3.addWidget(self.calendarWidget)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/microsoft-excel-2019-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon3)
        self.pushButton_12.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_7.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setIcon(icon3)
        self.pushButton_11.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_7.addWidget(self.pushButton_11)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(200, 0))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox_ISIN = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_ISIN.setCurrentText("")
        self.comboBox_ISIN.setObjectName("comboBox_ISIN")
        self.horizontalLayout_6.addWidget(self.comboBox_ISIN)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/search-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_6.addWidget(self.pushButton_10)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_nombre = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_nombre)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_prix = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_prix.setObjectName("lineEdit_prix")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_prix)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_valo = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_valo.setObjectName("lineEdit_valo")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_valo)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_valoAcqui = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_valoAcqui.setObjectName("lineEdit_valoAcqui")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_valoAcqui)
        self.label_date = QtWidgets.QLabel(self.groupBox_2)
        self.label_date.setObjectName("label_date")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_date)
        self.label_nominal = QtWidgets.QLabel(self.groupBox_2)
        self.label_nominal.setObjectName("label_nominal")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_nominal)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/edit-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/delete-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon6)
        self.pushButton_8.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/statistics-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon7)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_4.addWidget(self.pushButton_9)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        MainWindowPortefeuille.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowPortefeuille)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1483, 21))
        self.menubar.setObjectName("menubar")
        MainWindowPortefeuille.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowPortefeuille)
        self.statusbar.setObjectName("statusbar")
        MainWindowPortefeuille.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindowPortefeuille)
        self.toolBar.setObjectName("toolBar")
        MainWindowPortefeuille.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionClient = QtWidgets.QAction(MainWindowPortefeuille)
        self.actionClient.setObjectName("actionClient")
        self.action_addClient = QtWidgets.QAction(MainWindowPortefeuille)
        self.action_addClient.setCheckable(True)
        self.action_addClient.setIcon(icon1)
        self.action_addClient.setObjectName("action_addClient")
        self.action_ficheClient = QtWidgets.QAction(MainWindowPortefeuille)
        self.action_ficheClient.setCheckable(True)
        self.action_ficheClient.setObjectName("action_ficheClient")
        self.actionPortefeuille = QtWidgets.QAction(MainWindowPortefeuille)
        self.actionPortefeuille.setObjectName("actionPortefeuille")
        self.action_deletePortefeuille = QtWidgets.QAction(MainWindowPortefeuille)
        self.action_deletePortefeuille.setCheckable(True)
        self.action_deletePortefeuille.setIcon(icon6)
        self.action_deletePortefeuille.setObjectName("action_deletePortefeuille")
        self.action_modifyPortefeuilleName = QtWidgets.QAction(MainWindowPortefeuille)
        self.action_modifyPortefeuilleName.setCheckable(True)
        self.action_modifyPortefeuilleName.setIcon(icon5)
        self.action_modifyPortefeuilleName.setObjectName("action_modifyPortefeuilleName")
        self.toolBar.addAction(self.actionClient)
        self.toolBar.addAction(self.action_addClient)
        self.toolBar.addAction(self.action_ficheClient)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPortefeuille)
        self.toolBar.addAction(self.action_deletePortefeuille)
        self.toolBar.addAction(self.action_modifyPortefeuilleName)

        self.retranslateUi(MainWindowPortefeuille)
        QtCore.QMetaObject.connectSlotsByName(MainWindowPortefeuille)

    def retranslateUi(self, MainWindowPortefeuille):
        _translate = QtCore.QCoreApplication.translate
        MainWindowPortefeuille.setWindowTitle(_translate("MainWindowPortefeuille", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindowPortefeuille", "Sélectionner le client puis le portefeuille"))
        self.btn_unlockClient.setText(_translate("MainWindowPortefeuille", "UnLock"))
        self.label.setText(_translate("MainWindowPortefeuille", "Liste des clients existants :"))
        self.label_2.setText(_translate("MainWindowPortefeuille", "Liste de ses portefeuilles :"))
        self.btn_unlockPortefeuille.setText(_translate("MainWindowPortefeuille", "UnLock"))
        self.btn_chooseClient.setText(_translate("MainWindowPortefeuille", "Choisir"))
        self.btn_choosePortefeuille.setText(_translate("MainWindowPortefeuille", "Choisir"))
        self.btn_newPortefeuille.setText(_translate("MainWindowPortefeuille", "Nouveau portefeuille"))
        self.label_portefeuilleChoisi.setText(_translate("MainWindowPortefeuille", "Portefeuille choisi :"))
        self.label_4.setText(_translate("MainWindowPortefeuille", "Liquidité :"))
        self.pushButton_4.setText(_translate("MainWindowPortefeuille", "Validier liquidité"))
        self.label_dateChoisie.setText(_translate("MainWindowPortefeuille", "Date choisie :"))
        self.pushButton_5.setText(_translate("MainWindowPortefeuille", "Transférer le dernier portefeuille"))
        self.pushButton_12.setText(_translate("MainWindowPortefeuille", "Importation XLS"))
        self.pushButton_11.setText(_translate("MainWindowPortefeuille", "Exportation XLS"))
        self.label_13.setText(_translate("MainWindowPortefeuille", "Nombres de lignes"))
        self.groupBox_2.setTitle(_translate("MainWindowPortefeuille", "Configuration"))
        self.label_5.setText(_translate("MainWindowPortefeuille", "TextLabel"))
        self.label_7.setText(_translate("MainWindowPortefeuille", "ISIN"))
        self.label_8.setText(_translate("MainWindowPortefeuille", "Nombre"))
        self.label_9.setText(_translate("MainWindowPortefeuille", "Prix d\'achat"))
        self.label_10.setText(_translate("MainWindowPortefeuille", "Date"))
        self.label_11.setText(_translate("MainWindowPortefeuille", "Nominal"))
        self.label_6.setText(_translate("MainWindowPortefeuille", "Valo"))
        self.label_12.setText(_translate("MainWindowPortefeuille", "Valo. Acqui"))
        self.label_date.setText(_translate("MainWindowPortefeuille", "TextLabel"))
        self.label_nominal.setText(_translate("MainWindowPortefeuille", "TextLabel"))
        self.pushButton_6.setText(_translate("MainWindowPortefeuille", "Ajouter la ligne"))
        self.pushButton_7.setText(_translate("MainWindowPortefeuille", "Modifier la ligne"))
        self.pushButton_8.setText(_translate("MainWindowPortefeuille", "Supprimer la ligne"))
        self.pushButton_9.setText(_translate("MainWindowPortefeuille", "Menu Visualisation"))
        self.toolBar.setWindowTitle(_translate("MainWindowPortefeuille", "toolBar"))
        self.actionClient.setText(_translate("MainWindowPortefeuille", "Client"))
        self.action_addClient.setText(_translate("MainWindowPortefeuille", "Ajouter un client"))
        self.action_ficheClient.setText(_translate("MainWindowPortefeuille", "Fiche Client"))
        self.actionPortefeuille.setText(_translate("MainWindowPortefeuille", "Portefeuille"))
        self.action_deletePortefeuille.setText(_translate("MainWindowPortefeuille", "Supprimer le portefeuille"))
        self.action_modifyPortefeuilleName.setText(_translate("MainWindowPortefeuille", "Modifier le nom du portefeuille"))

