# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AssistantClient.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowClient(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 327)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_Valider = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_Valider.setGeometry(QtCore.QRect(10, 10, 471, 271))
        self.tabWidget_Valider.setObjectName("tabWidget_Valider")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_Entreprise = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Entreprise.setGeometry(QtCore.QRect(160, 30, 191, 20))
        self.lineEdit_Entreprise.setObjectName("lineEdit_Entreprise")
        self.lineEdit_ContactName = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_ContactName.setGeometry(QtCore.QRect(160, 60, 191, 20))
        self.lineEdit_ContactName.setObjectName("lineEdit_ContactName")
        self.lineEdit_ContactForename = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_ContactForename.setGeometry(QtCore.QRect(160, 90, 191, 20))
        self.lineEdit_ContactForename.setObjectName("lineEdit_ContactForename")
        self.lineEdit_Mail = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Mail.setGeometry(QtCore.QRect(160, 120, 191, 20))
        self.lineEdit_Mail.setObjectName("lineEdit_Mail")
        self.label_Entreprise = QtWidgets.QLabel(self.tab)
        self.label_Entreprise.setGeometry(QtCore.QRect(60, 30, 91, 20))
        self.label_Entreprise.setObjectName("label_Entreprise")
        self.label_Name = QtWidgets.QLabel(self.tab)
        self.label_Name.setGeometry(QtCore.QRect(60, 60, 101, 20))
        self.label_Name.setObjectName("label_Name")
        self.label_Forename = QtWidgets.QLabel(self.tab)
        self.label_Forename.setGeometry(QtCore.QRect(60, 90, 111, 21))
        self.label_Forename.setObjectName("label_Forename")
        self.label_Mail = QtWidgets.QLabel(self.tab)
        self.label_Mail.setGeometry(QtCore.QRect(60, 120, 81, 16))
        self.label_Mail.setObjectName("label_Mail")
        self.pushButton_Valider = QtWidgets.QPushButton(self.tab)
        self.pushButton_Valider.setGeometry(QtCore.QRect(160, 170, 91, 21))
        self.pushButton_Valider.setObjectName("pushButton_Valider")
        self.tabWidget_Valider.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.fontComboBox_ModClient = QtWidgets.QFontComboBox(self.tab_2)
        self.fontComboBox_ModClient.setGeometry(QtCore.QRect(20, 20, 411, 22))
        self.fontComboBox_ModClient.setCurrentText("")
        self.fontComboBox_ModClient.setObjectName("fontComboBox_ModClient")
        self.labe_ModEntreprise = QtWidgets.QLabel(self.tab_2)
        self.labe_ModEntreprise.setGeometry(QtCore.QRect(20, 50, 131, 16))
        self.labe_ModEntreprise.setObjectName("labe_ModEntreprise")
        self.label_ModContactName = QtWidgets.QLabel(self.tab_2)
        self.label_ModContactName.setGeometry(QtCore.QRect(20, 80, 101, 16))
        self.label_ModContactName.setObjectName("label_ModContactName")
        self.label_ModContactForename = QtWidgets.QLabel(self.tab_2)
        self.label_ModContactForename.setGeometry(QtCore.QRect(20, 110, 111, 16))
        self.label_ModContactForename.setObjectName("label_ModContactForename")
        self.label_ModMail = QtWidgets.QLabel(self.tab_2)
        self.label_ModMail.setGeometry(QtCore.QRect(20, 140, 51, 16))
        self.label_ModMail.setObjectName("label_ModMail")
        self.lineEdit_ModEntreprise = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_ModEntreprise.setGeometry(QtCore.QRect(210, 50, 221, 20))
        self.lineEdit_ModEntreprise.setObjectName("lineEdit_ModEntreprise")
        self.lineEdit_ModContactName = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_ModContactName.setGeometry(QtCore.QRect(210, 80, 221, 20))
        self.lineEdit_ModContactName.setObjectName("lineEdit_ModContactName")
        self.lineEdit_ModContactForename = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_ModContactForename.setGeometry(QtCore.QRect(210, 110, 221, 20))
        self.lineEdit_ModContactForename.setObjectName("lineEdit_ModContactForename")
        self.lineEdit_ModMail = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_ModMail.setGeometry(QtCore.QRect(210, 140, 221, 20))
        self.lineEdit_ModMail.setObjectName("lineEdit_ModMail")
        self.pushButton_ModValider = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_ModValider.setGeometry(QtCore.QRect(180, 190, 75, 23))
        self.pushButton_ModValider.setObjectName("pushButton_ModValider")
        self.tabWidget_Valider.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.fontComboBox_SupprClient = QtWidgets.QFontComboBox(self.tab_3)
        self.fontComboBox_SupprClient.setGeometry(QtCore.QRect(20, 20, 411, 22))
        self.fontComboBox_SupprClient.setCurrentText("")
        self.fontComboBox_SupprClient.setObjectName("fontComboBox_SupprClient")
        self.pushButton_SupprValider = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_SupprValider.setGeometry(QtCore.QRect(180, 120, 75, 23))
        self.pushButton_SupprValider.setObjectName("pushButton_SupprValider")
        self.tabWidget_Valider.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_Valider.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Entreprise.setText(_translate("MainWindow", "Entreprise"))
        self.label_Name.setText(_translate("MainWindow", "Nom du contact"))
        self.label_Forename.setText(_translate("MainWindow", "Prénom du Contact"))
        self.label_Mail.setText(_translate("MainWindow", "Mail du Contact"))
        self.pushButton_Valider.setText(_translate("MainWindow", "Valider"))
        self.tabWidget_Valider.setTabText(self.tabWidget_Valider.indexOf(self.tab), _translate("MainWindow", "Client"))
        self.labe_ModEntreprise.setText(_translate("MainWindow", "Entreprise"))
        self.label_ModContactName.setText(_translate("MainWindow", "Nom du Contact"))
        self.label_ModContactForename.setText(_translate("MainWindow", "Prénom du Contact"))
        self.label_ModMail.setText(_translate("MainWindow", "E-Mail"))
        self.pushButton_ModValider.setText(_translate("MainWindow", "Valider"))
        self.tabWidget_Valider.setTabText(self.tabWidget_Valider.indexOf(self.tab_2), _translate("MainWindow", "Modifier un Client"))
        self.pushButton_SupprValider.setText(_translate("MainWindow", "Supprimer"))
        self.tabWidget_Valider.setTabText(self.tabWidget_Valider.indexOf(self.tab_3), _translate("MainWindow", "Supprimer un Client"))
