# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AssistantClient.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowClient(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 346)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_Valider = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_Valider.setGeometry(QtCore.QRect(0, 0, 501, 301))
        self.tabWidget_Valider.setObjectName("tabWidget_Valider")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_Valider = QtWidgets.QPushButton(self.tab)
        self.pushButton_Valider.setGeometry(QtCore.QRect(80, 230, 91, 21))
        self.pushButton_Valider.setObjectName("pushButton_Valider")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 451, 201))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_Entreprise = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_Entreprise.setObjectName("label_Entreprise")
        self.verticalLayout_5.addWidget(self.label_Entreprise)
        self.label_Name = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_Name.setObjectName("label_Name")
        self.verticalLayout_5.addWidget(self.label_Name)
        self.label_Forename = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_Forename.setObjectName("label_Forename")
        self.verticalLayout_5.addWidget(self.label_Forename)
        self.label_Mail = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_Mail.setObjectName("label_Mail")
        self.verticalLayout_5.addWidget(self.label_Mail)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_Entreprise = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_Entreprise.setObjectName("lineEdit_Entreprise")
        self.verticalLayout_6.addWidget(self.lineEdit_Entreprise)
        self.lineEdit_ContactName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_ContactName.setObjectName("lineEdit_ContactName")
        self.verticalLayout_6.addWidget(self.lineEdit_ContactName)
        self.lineEdit_ContactForename = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_ContactForename.setObjectName("lineEdit_ContactForename")
        self.verticalLayout_6.addWidget(self.lineEdit_ContactForename)
        self.lineEdit_Mail = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_Mail.setObjectName("lineEdit_Mail")
        self.verticalLayout_6.addWidget(self.lineEdit_Mail)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.tabWidget_Valider.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 441, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_ModClient = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_ModClient.setObjectName("comboBox_ModClient")
        self.verticalLayout.addWidget(self.comboBox_ModClient)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labe_ModEntreprise = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labe_ModEntreprise.setObjectName("labe_ModEntreprise")
        self.verticalLayout_2.addWidget(self.labe_ModEntreprise)
        self.label_ModContactName = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_ModContactName.setObjectName("label_ModContactName")
        self.verticalLayout_2.addWidget(self.label_ModContactName)
        self.label_ModContactForename = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_ModContactForename.setObjectName("label_ModContactForename")
        self.verticalLayout_2.addWidget(self.label_ModContactForename)
        self.label_ModMail = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_ModMail.setObjectName("label_ModMail")
        self.verticalLayout_2.addWidget(self.label_ModMail)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_ModEntreprise = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_ModEntreprise.setObjectName("lineEdit_ModEntreprise")
        self.verticalLayout_4.addWidget(self.lineEdit_ModEntreprise)
        self.lineEdit_ModContactName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_ModContactName.setObjectName("lineEdit_ModContactName")
        self.verticalLayout_4.addWidget(self.lineEdit_ModContactName)
        self.lineEdit_ModContactForename = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_ModContactForename.setObjectName("lineEdit_ModContactForename")
        self.verticalLayout_4.addWidget(self.lineEdit_ModContactForename)
        self.lineEdit_ModMail = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_ModMail.setObjectName("lineEdit_ModMail")
        self.verticalLayout_4.addWidget(self.lineEdit_ModMail)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_ModValider = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_ModValider.setObjectName("pushButton_ModValider")
        self.verticalLayout.addWidget(self.pushButton_ModValider)
        self.tabWidget_Valider.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_SupprValider = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_SupprValider.setGeometry(QtCore.QRect(150, 150, 141, 23))
        self.pushButton_SupprValider.setObjectName("pushButton_SupprValider")
        self.comboBox_SupprClient = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_SupprClient.setGeometry(QtCore.QRect(10, 70, 441, 22))
        self.comboBox_SupprClient.setObjectName("comboBox_SupprClient")
        self.tabWidget_Valider.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_Valider.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Valider.setText(_translate("MainWindow", "Valider"))
        self.label_Entreprise.setText(_translate("MainWindow", "Entreprise"))
        self.label_Name.setText(_translate("MainWindow", "Nom du contact"))
        self.label_Forename.setText(_translate("MainWindow", "Prénom du Contact"))
        self.label_Mail.setText(_translate("MainWindow", "Mail du Contact"))
        self.tabWidget_Valider.setTabText(self.tabWidget_Valider.indexOf(self.tab), _translate("MainWindow", "Client"))
        self.labe_ModEntreprise.setText(_translate("MainWindow", "Entreprise"))
        self.label_ModContactName.setText(_translate("MainWindow", "Nom du Contact"))
        self.label_ModContactForename.setText(_translate("MainWindow", "Prénom du Contact"))
        self.label_ModMail.setText(_translate("MainWindow", "E-Mail"))
        self.pushButton_ModValider.setText(_translate("MainWindow", "Valider"))
        self.tabWidget_Valider.setTabText(self.tabWidget_Valider.indexOf(self.tab_2), _translate("MainWindow", "Modifier un Client"))
        self.pushButton_SupprValider.setText(_translate("MainWindow", "Supprimer"))
        self.tabWidget_Valider.setTabText(self.tabWidget_Valider.indexOf(self.tab_3), _translate("MainWindow", "Supprimer un Client"))
import ressources_rc
