# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GestionnaireObligataire.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowObligation(object):
    def setupUi(self, MainWindowObligation):
        MainWindowObligation.setObjectName("MainWindowObligation")
        MainWindowObligation.resize(632, 785)
        self.centralwidget = QtWidgets.QWidget(MainWindowObligation)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(80, 740, 151, 17))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_Valider = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Valider.setGeometry(QtCore.QRect(320, 730, 161, 31))
        self.pushButton_Valider.setObjectName("pushButton_Valider")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 611, 721))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_ListeOblig = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ListeOblig.sizePolicy().hasHeightForWidth())
        self.label_ListeOblig.setSizePolicy(sizePolicy)
        self.label_ListeOblig.setObjectName("label_ListeOblig")
        self.verticalLayout_2.addWidget(self.label_ListeOblig)
        self.comboBox_ListeOblig = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_ListeOblig.setObjectName("comboBox_ListeOblig")
        self.verticalLayout_2.addWidget(self.comboBox_ListeOblig)
        self.pushBtton_NvlOblig = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushBtton_NvlOblig.sizePolicy().hasHeightForWidth())
        self.pushBtton_NvlOblig.setSizePolicy(sizePolicy)
        self.pushBtton_NvlOblig.setObjectName("pushBtton_NvlOblig")
        self.verticalLayout_2.addWidget(self.pushBtton_NvlOblig)
        self.label_SrchCode = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SrchCode.sizePolicy().hasHeightForWidth())
        self.label_SrchCode.setSizePolicy(sizePolicy)
        self.label_SrchCode.setObjectName("label_SrchCode")
        self.verticalLayout_2.addWidget(self.label_SrchCode)
        self.lineEdit_SrchCode = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_SrchCode.setObjectName("lineEdit_SrchCode")
        self.verticalLayout_2.addWidget(self.lineEdit_SrchCode)
        self.textEdit_SrchOblig = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_SrchOblig.sizePolicy().hasHeightForWidth())
        self.textEdit_SrchOblig.setSizePolicy(sizePolicy)
        self.textEdit_SrchOblig.setObjectName("textEdit_SrchOblig")
        self.verticalLayout_2.addWidget(self.textEdit_SrchOblig)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_ISN = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_ISN.setObjectName("label_ISN")
        self.verticalLayout_4.addWidget(self.label_ISN)
        self.label_Libelle = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Libelle.setObjectName("label_Libelle")
        self.verticalLayout_4.addWidget(self.label_Libelle)
        self.label_Ticker = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Ticker.setObjectName("label_Ticker")
        self.verticalLayout_4.addWidget(self.label_Ticker)
        self.label_Remb = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Remb.setObjectName("label_Remb")
        self.verticalLayout_4.addWidget(self.label_Remb)
        self.label_Type = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Type.setObjectName("label_Type")
        self.verticalLayout_4.addWidget(self.label_Type)
        self.label_Nominal = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Nominal.setObjectName("label_Nominal")
        self.verticalLayout_4.addWidget(self.label_Nominal)
        self.label_Cours = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Cours.setObjectName("label_Cours")
        self.verticalLayout_4.addWidget(self.label_Cours)
        self.label_Coupon = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Coupon.setObjectName("label_Coupon")
        self.verticalLayout_4.addWidget(self.label_Coupon)
        self.label_DevisePassee = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_DevisePassee.setObjectName("label_DevisePassee")
        self.verticalLayout_4.addWidget(self.label_DevisePassee)
        self.label_DevisePrst = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_DevisePrst.setObjectName("label_DevisePrst")
        self.verticalLayout_4.addWidget(self.label_DevisePrst)
        self.label_Region = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Region.setObjectName("label_Region")
        self.verticalLayout_4.addWidget(self.label_Region)
        self.label_SsSecteur = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_SsSecteur.setObjectName("label_SsSecteur")
        self.verticalLayout_4.addWidget(self.label_SsSecteur)
        self.label_Maturite = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Maturite.setObjectName("label_Maturite")
        self.verticalLayout_4.addWidget(self.label_Maturite)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_ISIN = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_ISIN.setObjectName("lineEdit_ISIN")
        self.verticalLayout_3.addWidget(self.lineEdit_ISIN)
        self.lineEdit_Libelle = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_Libelle.setObjectName("lineEdit_Libelle")
        self.verticalLayout_3.addWidget(self.lineEdit_Libelle)
        self.comboBox_Ticker = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_Ticker.setObjectName("comboBox_Ticker")
        self.verticalLayout_3.addWidget(self.comboBox_Ticker)
        self.spinBox_rembrmt = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_rembrmt.setObjectName("spinBox_rembrmt")
        self.verticalLayout_3.addWidget(self.spinBox_rembrmt)
        self.comboBox_Type = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.verticalLayout_3.addWidget(self.comboBox_Type)
        self.lineEdit_Nominal = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_Nominal.setObjectName("lineEdit_Nominal")
        self.verticalLayout_3.addWidget(self.lineEdit_Nominal)
        self.lineEdit_Cours = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_Cours.setObjectName("lineEdit_Cours")
        self.verticalLayout_3.addWidget(self.lineEdit_Cours)
        self.lineEdit_Coupon = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_Coupon.setObjectName("lineEdit_Coupon")
        self.verticalLayout_3.addWidget(self.lineEdit_Coupon)
        self.lineEdit_DevisePassee = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_DevisePassee.setObjectName("lineEdit_DevisePassee")
        self.verticalLayout_3.addWidget(self.lineEdit_DevisePassee)
        self.lineEdit_DevisePrst = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_DevisePrst.setObjectName("lineEdit_DevisePrst")
        self.verticalLayout_3.addWidget(self.lineEdit_DevisePrst)
        self.comboBox_Region = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_Region.setObjectName("comboBox_Region")
        self.verticalLayout_3.addWidget(self.comboBox_Region)
        self.comboBox_SsSecteur = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_SsSecteur.setObjectName("comboBox_SsSecteur")
        self.verticalLayout_3.addWidget(self.comboBox_SsSecteur)
        self.comboBox_Maturite = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_Maturite.setObjectName("comboBox_Maturite")
        self.verticalLayout_3.addWidget(self.comboBox_Maturite)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.label_SrchTicker = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_SrchTicker.setObjectName("label_SrchTicker")
        self.verticalLayout.addWidget(self.label_SrchTicker)
        self.lineEdit_SrchTicker = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_SrchTicker.setObjectName("lineEdit_SrchTicker")
        self.verticalLayout.addWidget(self.lineEdit_SrchTicker)
        self.textEdit_SrchTicker = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_SrchTicker.setObjectName("textEdit_SrchTicker")
        self.verticalLayout.addWidget(self.textEdit_SrchTicker)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_Rendement = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Rendement.setObjectName("label_Rendement")
        self.verticalLayout_6.addWidget(self.label_Rendement)
        self.label_Duration = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Duration.setObjectName("label_Duration")
        self.verticalLayout_6.addWidget(self.label_Duration)
        self.label_ClasseDuration = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_ClasseDuration.setObjectName("label_ClasseDuration")
        self.verticalLayout_6.addWidget(self.label_ClasseDuration)
        self.label_SpreadBund = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_SpreadBund.setObjectName("label_SpreadBund")
        self.verticalLayout_6.addWidget(self.label_SpreadBund)
        self.label_InteretsCourus = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_InteretsCourus.setObjectName("label_InteretsCourus")
        self.verticalLayout_6.addWidget(self.label_InteretsCourus)
        self.label_Sensibilite = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Sensibilite.setObjectName("label_Sensibilite")
        self.verticalLayout_6.addWidget(self.label_Sensibilite)
        self.label_Convexite = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Convexite.setObjectName("label_Convexite")
        self.verticalLayout_6.addWidget(self.label_Convexite)
        self.label_AvgLife = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_AvgLife.setObjectName("label_AvgLife")
        self.verticalLayout_6.addWidget(self.label_AvgLife)
        self.label_Indexation = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Indexation.setObjectName("label_Indexation")
        self.verticalLayout_6.addWidget(self.label_Indexation)
        self.label_Rating = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Rating.setObjectName("label_Rating")
        self.verticalLayout_6.addWidget(self.label_Rating)
        self.label_RatingSP = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_RatingSP.setObjectName("label_RatingSP")
        self.verticalLayout_6.addWidget(self.label_RatingSP)
        self.label_RatingMoody = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_RatingMoody.setObjectName("label_RatingMoody")
        self.verticalLayout_6.addWidget(self.label_RatingMoody)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_Rendement = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_Rendement.setObjectName("lineEdit_Rendement")
        self.verticalLayout_5.addWidget(self.lineEdit_Rendement)
        self.lineEdit_Duration = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_Duration.setObjectName("lineEdit_Duration")
        self.verticalLayout_5.addWidget(self.lineEdit_Duration)
        self.comboBox_ClasseDuration = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_ClasseDuration.setObjectName("comboBox_ClasseDuration")
        self.verticalLayout_5.addWidget(self.comboBox_ClasseDuration)
        self.lineEdit_SpreadBund = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_SpreadBund.setObjectName("lineEdit_SpreadBund")
        self.verticalLayout_5.addWidget(self.lineEdit_SpreadBund)
        self.lineEdit_InteretsCourus = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_InteretsCourus.setObjectName("lineEdit_InteretsCourus")
        self.verticalLayout_5.addWidget(self.lineEdit_InteretsCourus)
        self.lineEdit_Sensibilite = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_Sensibilite.setObjectName("lineEdit_Sensibilite")
        self.verticalLayout_5.addWidget(self.lineEdit_Sensibilite)
        self.lineEdit_Convexite = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_Convexite.setObjectName("lineEdit_Convexite")
        self.verticalLayout_5.addWidget(self.lineEdit_Convexite)
        self.lineEdit_AvgLife = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_AvgLife.setObjectName("lineEdit_AvgLife")
        self.verticalLayout_5.addWidget(self.lineEdit_AvgLife)
        self.lineEdit_Indexation = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_Indexation.setObjectName("lineEdit_Indexation")
        self.verticalLayout_5.addWidget(self.lineEdit_Indexation)
        self.comboBox_Rating = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_Rating.setObjectName("comboBox_Rating")
        self.verticalLayout_5.addWidget(self.comboBox_Rating)
        self.comboBox_RatingSP = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_RatingSP.setObjectName("comboBox_RatingSP")
        self.verticalLayout_5.addWidget(self.comboBox_RatingSP)
        self.comboBox_RatingMoody = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_RatingMoody.setObjectName("comboBox_RatingMoody")
        self.verticalLayout_5.addWidget(self.comboBox_RatingMoody)
        self.comboBox_RatingFitch = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_RatingFitch.setObjectName("comboBox_RatingFitch")
        self.verticalLayout_5.addWidget(self.comboBox_RatingFitch)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindowObligation.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowObligation)
        self.statusbar.setObjectName("statusbar")
        MainWindowObligation.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowObligation)
        QtCore.QMetaObject.connectSlotsByName(MainWindowObligation)

    def retranslateUi(self, MainWindowObligation):
        _translate = QtCore.QCoreApplication.translate
        MainWindowObligation.setWindowTitle(_translate("MainWindowObligation", "MainWindow"))
        self.checkBox.setText(_translate("MainWindowObligation", "Mise à jour automatique"))
        self.pushButton_Valider.setText(_translate("MainWindowObligation", "Valider"))
        self.label_ListeOblig.setText(_translate("MainWindowObligation", "Liste des obligations"))
        self.pushBtton_NvlOblig.setText(_translate("MainWindowObligation", "Nouvelle obligation"))
        self.label_SrchCode.setText(_translate("MainWindowObligation", "Recherche par code  "))
        self.label_ISN.setText(_translate("MainWindowObligation", "ISIN"))
        self.label_Libelle.setText(_translate("MainWindowObligation", "Libelle"))
        self.label_Ticker.setText(_translate("MainWindowObligation", "Ticker"))
        self.label_Remb.setText(_translate("MainWindowObligation", "Taux Remb"))
        self.label_Type.setText(_translate("MainWindowObligation", "Type"))
        self.label_Nominal.setText(_translate("MainWindowObligation", "Nominal"))
        self.label_Cours.setText(_translate("MainWindowObligation", "Cours"))
        self.label_Coupon.setText(_translate("MainWindowObligation", "Coupon"))
        self.label_DevisePassee.setText(_translate("MainWindowObligation", "Devise Acquisition"))
        self.label_DevisePrst.setText(_translate("MainWindowObligation", "Devise Actuelle"))
        self.label_Region.setText(_translate("MainWindowObligation", "Région"))
        self.label_SsSecteur.setText(_translate("MainWindowObligation", "Sous Secteur"))
        self.label_Maturite.setText(_translate("MainWindowObligation", "Maturite"))
        self.label_SrchTicker.setText(_translate("MainWindowObligation", "Recherche par Ticker"))
        self.label_Rendement.setText(_translate("MainWindowObligation", "Rendement"))
        self.label_Duration.setText(_translate("MainWindowObligation", "Duration"))
        self.label_ClasseDuration.setText(_translate("MainWindowObligation", "Classe Duration"))
        self.label_SpreadBund.setText(_translate("MainWindowObligation", "Spread Bund"))
        self.label_InteretsCourus.setText(_translate("MainWindowObligation", "Intérêts Courus"))
        self.label_Sensibilite.setText(_translate("MainWindowObligation", "Sensibilité"))
        self.label_Convexite.setText(_translate("MainWindowObligation", "Convexite"))
        self.label_AvgLife.setText(_translate("MainWindowObligation", "Vie Moyenne"))
        self.label_Indexation.setText(_translate("MainWindowObligation", "Indéxation"))
        self.label_Rating.setText(_translate("MainWindowObligation", "Rating"))
        self.label_RatingSP.setText(_translate("MainWindowObligation", "Rating SP"))
        self.label_RatingMoody.setText(_translate("MainWindowObligation", "Rating MOODY"))
        self.label.setText(_translate("MainWindowObligation", "Rating FITCH"))
import ressources_rc
