# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GestionnaireObligataire.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowObligation(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(360, 20, 241, 161))
        self.calendarWidget.setObjectName("calendarWidget")
        self.comboBox_ListeOblig = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ListeOblig.setGeometry(QtCore.QRect(10, 40, 271, 22))
        self.comboBox_ListeOblig.setObjectName("comboBox_ListeOblig")
        self.label_ListeOblig = QtWidgets.QLabel(self.centralwidget)
        self.label_ListeOblig.setGeometry(QtCore.QRect(10, 20, 231, 20))
        self.label_ListeOblig.setObjectName("label_ListeOblig")
        self.pushBtton_NvlOblig = QtWidgets.QPushButton(self.centralwidget)
        self.pushBtton_NvlOblig.setGeometry(QtCore.QRect(10, 70, 271, 81))
        self.pushBtton_NvlOblig.setObjectName("pushBtton_NvlOblig")
        self.lineEdit_SrchCode = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_SrchCode.setGeometry(QtCore.QRect(10, 190, 271, 20))
        self.lineEdit_SrchCode.setObjectName("lineEdit_SrchCode")
        self.textEdit_SrchOblig = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_SrchOblig.setGeometry(QtCore.QRect(10, 220, 271, 71))
        self.textEdit_SrchOblig.setObjectName("textEdit_SrchOblig")
        self.lineEdit_SrchTicker = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_SrchTicker.setGeometry(QtCore.QRect(310, 190, 311, 20))
        self.lineEdit_SrchTicker.setObjectName("lineEdit_SrchTicker")
        self.textEdit_SrchTicker = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_SrchTicker.setGeometry(QtCore.QRect(310, 220, 311, 71))
        self.textEdit_SrchTicker.setObjectName("textEdit_SrchTicker")
        self.lineEdit_ISIN = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ISIN.setGeometry(QtCore.QRect(100, 310, 181, 20))
        self.lineEdit_ISIN.setObjectName("lineEdit_ISIN")
        self.label_ISN = QtWidgets.QLabel(self.centralwidget)
        self.label_ISN.setGeometry(QtCore.QRect(10, 310, 47, 21))
        self.label_ISN.setObjectName("label_ISN")
        self.fontComboBox_Ticker = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox_Ticker.setGeometry(QtCore.QRect(100, 360, 181, 22))
        self.fontComboBox_Ticker.setCurrentText("")
        self.fontComboBox_Ticker.setObjectName("fontComboBox_Ticker")
        self.spinBox_rembrmt = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_rembrmt.setGeometry(QtCore.QRect(100, 380, 181, 22))
        self.spinBox_rembrmt.setObjectName("spinBox_rembrmt")
        self.fontComboBox_Type = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox_Type.setGeometry(QtCore.QRect(100, 400, 181, 22))
        self.fontComboBox_Type.setCurrentText("")
        self.fontComboBox_Type.setObjectName("fontComboBox_Type")
        self.lineEdit_Nominal = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Nominal.setGeometry(QtCore.QRect(100, 430, 181, 20))
        self.lineEdit_Nominal.setObjectName("lineEdit_Nominal")
        self.lineEdit_Cours = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Cours.setGeometry(QtCore.QRect(100, 450, 181, 20))
        self.lineEdit_Cours.setObjectName("lineEdit_Cours")
        self.lineEdit_Coupon = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Coupon.setGeometry(QtCore.QRect(100, 470, 181, 20))
        self.lineEdit_Coupon.setObjectName("lineEdit_Coupon")
        self.lineEdit_DevisePassee = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_DevisePassee.setGeometry(QtCore.QRect(100, 490, 181, 20))
        self.lineEdit_DevisePassee.setObjectName("lineEdit_DevisePassee")
        self.lineEdit_DevisePrst = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_DevisePrst.setGeometry(QtCore.QRect(100, 510, 181, 20))
        self.lineEdit_DevisePrst.setObjectName("lineEdit_DevisePrst")
        self.fontComboBox_Maturite = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox_Maturite.setGeometry(QtCore.QRect(100, 550, 181, 22))
        self.fontComboBox_Maturite.setObjectName("fontComboBox_Maturite")
        self.fontComboBox_Region = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox_Region.setGeometry(QtCore.QRect(100, 590, 181, 22))
        self.fontComboBox_Region.setCurrentText("")
        self.fontComboBox_Region.setObjectName("fontComboBox_Region")
        self.fontComboBox_SsSecteur = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox_SsSecteur.setGeometry(QtCore.QRect(100, 610, 181, 22))
        self.fontComboBox_SsSecteur.setCurrentText("")
        self.fontComboBox_SsSecteur.setObjectName("fontComboBox_SsSecteur")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(100, 640, 151, 17))
        self.checkBox.setObjectName("checkBox")
        self.label_Ticker = QtWidgets.QLabel(self.centralwidget)
        self.label_Ticker.setGeometry(QtCore.QRect(10, 360, 47, 21))
        self.label_Ticker.setObjectName("label_Ticker")
        self.label_Remb = QtWidgets.QLabel(self.centralwidget)
        self.label_Remb.setGeometry(QtCore.QRect(10, 380, 61, 21))
        self.label_Remb.setObjectName("label_Remb")
        self.label_Type = QtWidgets.QLabel(self.centralwidget)
        self.label_Type.setGeometry(QtCore.QRect(10, 400, 47, 16))
        self.label_Type.setObjectName("label_Type")
        self.label_Nominal = QtWidgets.QLabel(self.centralwidget)
        self.label_Nominal.setGeometry(QtCore.QRect(10, 430, 61, 21))
        self.label_Nominal.setObjectName("label_Nominal")
        self.label_Cours = QtWidgets.QLabel(self.centralwidget)
        self.label_Cours.setGeometry(QtCore.QRect(10, 450, 47, 21))
        self.label_Cours.setObjectName("label_Cours")
        self.label_Coupon = QtWidgets.QLabel(self.centralwidget)
        self.label_Coupon.setGeometry(QtCore.QRect(10, 470, 47, 21))
        self.label_Coupon.setObjectName("label_Coupon")
        self.label_DevisePassee = QtWidgets.QLabel(self.centralwidget)
        self.label_DevisePassee.setGeometry(QtCore.QRect(10, 490, 91, 16))
        self.label_DevisePassee.setObjectName("label_DevisePassee")
        self.label_DevisePrst = QtWidgets.QLabel(self.centralwidget)
        self.label_DevisePrst.setGeometry(QtCore.QRect(10, 510, 81, 16))
        self.label_DevisePrst.setObjectName("label_DevisePrst")
        self.label_Region = QtWidgets.QLabel(self.centralwidget)
        self.label_Region.setGeometry(QtCore.QRect(10, 590, 61, 20))
        self.label_Region.setObjectName("label_Region")
        self.label_SsSecteur = QtWidgets.QLabel(self.centralwidget)
        self.label_SsSecteur.setGeometry(QtCore.QRect(10, 612, 71, 16))
        self.label_SsSecteur.setObjectName("label_SsSecteur")
        self.lineEdit_Libelle = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Libelle.setGeometry(QtCore.QRect(440, 310, 181, 20))
        self.lineEdit_Libelle.setObjectName("lineEdit_Libelle")
        self.label_Libelle = QtWidgets.QLabel(self.centralwidget)
        self.label_Libelle.setGeometry(QtCore.QRect(310, 310, 47, 16))
        self.label_Libelle.setObjectName("label_Libelle")
        self.label_Rendement = QtWidgets.QLabel(self.centralwidget)
        self.label_Rendement.setGeometry(QtCore.QRect(310, 360, 81, 16))
        self.label_Rendement.setObjectName("label_Rendement")
        self.lineEdit_Rendement = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Rendement.setGeometry(QtCore.QRect(440, 360, 181, 20))
        self.lineEdit_Rendement.setObjectName("lineEdit_Rendement")
        self.lineEdit_Duration = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Duration.setGeometry(QtCore.QRect(440, 380, 181, 20))
        self.lineEdit_Duration.setObjectName("lineEdit_Duration")
        self.label_Duration = QtWidgets.QLabel(self.centralwidget)
        self.label_Duration.setGeometry(QtCore.QRect(310, 380, 61, 16))
        self.label_Duration.setObjectName("label_Duration")
        self.fontComboBo_ClasseDuration = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBo_ClasseDuration.setGeometry(QtCore.QRect(440, 400, 181, 22))
        self.fontComboBo_ClasseDuration.setCurrentText("")
        self.fontComboBo_ClasseDuration.setObjectName("fontComboBo_ClasseDuration")
        self.label_ClasseDuration = QtWidgets.QLabel(self.centralwidget)
        self.label_ClasseDuration.setGeometry(QtCore.QRect(310, 402, 91, 16))
        self.label_ClasseDuration.setObjectName("label_ClasseDuration")
        self.lineEdit_SpreadBund = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_SpreadBund.setGeometry(QtCore.QRect(440, 420, 181, 20))
        self.lineEdit_SpreadBund.setObjectName("lineEdit_SpreadBund")
        self.label_SpreadBund = QtWidgets.QLabel(self.centralwidget)
        self.label_SpreadBund.setGeometry(QtCore.QRect(310, 420, 141, 16))
        self.label_SpreadBund.setObjectName("label_SpreadBund")
        self.lineEdit_InteretsCourus = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_InteretsCourus.setGeometry(QtCore.QRect(440, 440, 181, 20))
        self.lineEdit_InteretsCourus.setObjectName("lineEdit_InteretsCourus")
        self.label_InteretsCourus = QtWidgets.QLabel(self.centralwidget)
        self.label_InteretsCourus.setGeometry(QtCore.QRect(310, 440, 91, 16))
        self.label_InteretsCourus.setObjectName("label_InteretsCourus")
        self.lineEdit_Sensibilite = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Sensibilite.setGeometry(QtCore.QRect(440, 460, 181, 20))
        self.lineEdit_Sensibilite.setObjectName("lineEdit_Sensibilite")
        self.label_Sensibilite = QtWidgets.QLabel(self.centralwidget)
        self.label_Sensibilite.setGeometry(QtCore.QRect(310, 460, 101, 16))
        self.label_Sensibilite.setObjectName("label_Sensibilite")
        self.lineEdit_Convexite = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Convexite.setGeometry(QtCore.QRect(440, 480, 181, 20))
        self.lineEdit_Convexite.setObjectName("lineEdit_Convexite")
        self.label_Convexite = QtWidgets.QLabel(self.centralwidget)
        self.label_Convexite.setGeometry(QtCore.QRect(310, 480, 91, 16))
        self.label_Convexite.setObjectName("label_Convexite")
        self.lineEdit_AvgLife = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_AvgLife.setGeometry(QtCore.QRect(440, 500, 181, 20))
        self.lineEdit_AvgLife.setObjectName("lineEdit_AvgLife")
        self.label_AvgLife = QtWidgets.QLabel(self.centralwidget)
        self.label_AvgLife.setGeometry(QtCore.QRect(310, 500, 71, 16))
        self.label_AvgLife.setObjectName("label_AvgLife")
        self.lineEdit_Indexation = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Indexation.setGeometry(QtCore.QRect(440, 520, 181, 20))
        self.lineEdit_Indexation.setObjectName("lineEdit_Indexation")
        self.label_Indexation = QtWidgets.QLabel(self.centralwidget)
        self.label_Indexation.setGeometry(QtCore.QRect(310, 520, 71, 16))
        self.label_Indexation.setObjectName("label_Indexation")
        self.fontComboBox_Rating = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox_Rating.setGeometry(QtCore.QRect(440, 560, 181, 22))
        self.fontComboBox_Rating.setCurrentText("")
        self.fontComboBox_Rating.setObjectName("fontComboBox_Rating")
        self.label_Rating = QtWidgets.QLabel(self.centralwidget)
        self.label_Rating.setGeometry(QtCore.QRect(310, 560, 81, 16))
        self.label_Rating.setObjectName("label_Rating")
        self.label_RatingSP = QtWidgets.QLabel(self.centralwidget)
        self.label_RatingSP.setGeometry(QtCore.QRect(310, 580, 61, 20))
        self.label_RatingSP.setObjectName("label_RatingSP")
        self.fontComboBox_RatingSP = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox_RatingSP.setGeometry(QtCore.QRect(440, 580, 181, 22))
        self.fontComboBox_RatingSP.setCurrentText("")
        self.fontComboBox_RatingSP.setObjectName("fontComboBox_RatingSP")
        self.fontComboBox_RatingMoody = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox_RatingMoody.setGeometry(QtCore.QRect(440, 600, 181, 22))
        self.fontComboBox_RatingMoody.setCurrentText("")
        self.fontComboBox_RatingMoody.setObjectName("fontComboBox_RatingMoody")
        self.label_RatingMoody = QtWidgets.QLabel(self.centralwidget)
        self.label_RatingMoody.setGeometry(QtCore.QRect(310, 602, 121, 16))
        self.label_RatingMoody.setObjectName("label_RatingMoody")
        self.fontComboBox_RatingFitch = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox_RatingFitch.setGeometry(QtCore.QRect(440, 620, 181, 22))
        self.fontComboBox_RatingFitch.setCurrentText("")
        self.fontComboBox_RatingFitch.setObjectName("fontComboBox_RatingFitch")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 620, 91, 16))
        self.label.setObjectName("label")
        self.pushButton_Valider = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Valider.setGeometry(QtCore.QRect(300, 650, 161, 31))
        self.pushButton_Valider.setObjectName("pushButton_Valider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_ListeOblig.setText(_translate("MainWindow", "Liste des obligations"))
        self.pushBtton_NvlOblig.setText(_translate("MainWindow", "Nouvelle obligation"))
        self.label_ISN.setText(_translate("MainWindow", "ISIN"))
        self.fontComboBox_Maturite.setCurrentText(_translate("MainWindow", "Maturité"))
        self.checkBox.setText(_translate("MainWindow", "Mise à jour automatique"))
        self.label_Ticker.setText(_translate("MainWindow", "Ticker"))
        self.label_Remb.setText(_translate("MainWindow", "Taux Remb"))
        self.label_Type.setText(_translate("MainWindow", "Type"))
        self.label_Nominal.setText(_translate("MainWindow", "Nominal"))
        self.label_Cours.setText(_translate("MainWindow", "Cours"))
        self.label_Coupon.setText(_translate("MainWindow", "Coupon"))
        self.label_DevisePassee.setText(_translate("MainWindow", "Devise Acquisition"))
        self.label_DevisePrst.setText(_translate("MainWindow", "Devise Actuelle"))
        self.label_Region.setText(_translate("MainWindow", "Région"))
        self.label_SsSecteur.setText(_translate("MainWindow", "Sous Secteur"))
        self.label_Libelle.setText(_translate("MainWindow", "Libelle"))
        self.label_Rendement.setText(_translate("MainWindow", "Rendement"))
        self.label_Duration.setText(_translate("MainWindow", "Duration"))
        self.label_ClasseDuration.setText(_translate("MainWindow", "Classe Duration"))
        self.label_SpreadBund.setText(_translate("MainWindow", "Spread Bund"))
        self.label_InteretsCourus.setText(_translate("MainWindow", "Intérêts Courus"))
        self.label_Sensibilite.setText(_translate("MainWindow", "Sensibilité"))
        self.label_Convexite.setText(_translate("MainWindow", "Convexite"))
        self.label_AvgLife.setText(_translate("MainWindow", "Vie Moyenne"))
        self.label_Indexation.setText(_translate("MainWindow", "Indéxation"))
        self.label_Rating.setText(_translate("MainWindow", "Rating"))
        self.label_RatingSP.setText(_translate("MainWindow", "Rating SP"))
        self.label_RatingMoody.setText(_translate("MainWindow", "Rating MOODY"))
        self.label.setText(_translate("MainWindow", "Rating FITCH"))
        self.pushButton_Valider.setText(_translate("MainWindow", "Valider"))
